language: java

addons:
  sonarcloud:
    organization: "cardhive"
    token:
      secure: "bQte7HN0B/jrePjKdrU+oH9k8VuDf9q2g4gSOplCHV80P9yUfeAWeEtcrgpIriIY9CK1OwZeDAwapgP7VjcFKk5TrR8Z8xVgOh2JPisH35g93onFGCU71e9+nrIPJF1i3ucwNUr50PpOMjEcU0Pnd521c80XVsNs30s/iXsgQiwAdLHbrqaPlVw7zKLAt8SkGUPXuI6z2rykYNJCs73TMwuqYvWC+P3D412ThT/WqMav95eZcoA/gxTwMntiVC63FnBLyDXiHxfx741d7v2sWSu4R5+XBZ8gF2g94U7r1nfCLQAIg8GiDfP1SOeqfgqmxY+VqPhmtnJJUXo8KVNGic5wS3MJrJi3wFFWZqjClFkqNUkmc4o/8pMV8hNKNKSoteEQYGH43Q2oNifcSKcdpHCisT1xPhg2c8C3xvcNqg9SeT/LpaT4nRfpLC94qqaQTbIrv/SBszPnEo9U1OnSU5YHy/ox6tfFHY0uXPdoNG9XJd7slU2VnDs7NfJKe1zb+E3CuMz8CcPPpTwjIpIyiOgnSLU/8k4qwJpC2rHv+ThU6X+TCmrSf8urxc/utpNXdV4Hm/0GNzfvmMgIEGaMEKbmhS9FhWX5JFnhfOLk/YDBrMJD8lSA7YWx+n2iHGBhBnc4seReCIHqVCXg5Nj4YU4Q0nCjy8zU+1exmAiWOJw="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
