language: java

addons:
  sonarcloud:
    organization: "cardhive"
    token:
      secure: "MjuCmeDaalzLyqGa+qyp5eucKo/7aojcZdN7gMH5S1H73/+we9T//NSEcA06RyzelLW0RdhjGyIl9mm/BE3wYesPsvD+2uLeylwgpyTi/jv5FV6HMJIlyf1cKSRbGxKo0Kp1wJYlNCtHn0mjgMXSmrYu9zcCj+0UZdgcWIntacwSrgjPpvg41P5oc0qzngNTtyL2Dr/9mpFEvv+S4ISYnUvn2F2dupAZ5TQ2TWhQ1M6m2QS+mImbLOIiUPdsgc5tNdN+3/if+aPb7HV5HWMwMQ8b9lOCN/DMhsC5Ch2/RnlQuEcxAXwJbvrkVAt/r54uhDufgtiW1+078YI9GiYUlbhJcDHn8dd4l2PUohK0QCwcIIG/q/Ps8RicIZDcKy5rfibZyb6rTSOReknkCpE2iucjCYPJg4sGaA/NGc6PH2x9HfZfFnPP0EA+0viCkXWX9QJpVI1yLSa3wwD6NoPApxgvXqyIixlvthNj5hrbovBBJqMYQzTU9EHxC0nkKqbjA7VKgHIkNHQfl76legqfU+zPDZFj5ErJ1Lrh39Zdgs/ud72EEotcMsiyqQndJY70vWOgPnYAEE8M2GFG6SmByR5l7h1g98sJhp1O4jlg0icNjnwlY3QlUbstxC4Zc2B0NvwWdJS/38PtUeI04J43m3QXOQREksDML8BqlrQSqC4="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
